---
title: "Day 5 morning session"
author: "Leilanie Rubinstein"
format: html
execute: 
  warning: false
editor_options: 
  chunk_output_type: console
---

```{r}
#| message: false
# load libraries ----
library(tidyverse)
```

```{r}
#| include: false
# do some data exploration on the starwars df ----
head(starwars, n = 10)
tail(starwars)
dim(starwars)
```

```{r}
#| echo: true
ggplot(data = starwars, aes(x = height, y = mass, color = mass)) + 
  geom_point(color = "purple", size = 2) + 
  labs(x = "Height (cm)",
       y = "Mass (M)",
       title = "Here is my title")
```

- create a histogram of character heights
- update fill color to purple and the borders to orange
- update axis labels
- update your code chunk options so that only your code and output graph appear in the rendered doc

```{r}
#| echo: true
#| fig-cap: "This is my figure caption"
#| fig-alt: "this is some alt text"
ggplot(data = starwars, aes(x = height)) + 
  geom_histogram(fill = "purple", color = "orange") +
  labs(x = "Character Heights (cm)", y = "frequency")
```

`df$col_name1`

```{r}                                                        
(sw_height_mean <- round(mean(starwars$height, na.rm = TRUE), 3))
```










